name = "shreyachanth"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "shreyamedia"

[[kv_namespaces]]
binding = "FEED_CACHE"
id = "7178dda5d9db42a3be57dbcd2efd4975"

[[kv_namespaces]]
binding = "RL"
id = "1cabf0caa9944963916cf7d286ca639f"
